import {
  CORE_V1_MAX_COMBAT_TICK,
  CORE_V1_MAX_COMBO_EVENTS,
  CORE_V1_MAX_EVENT_QUEUE_SIZE,
  CORE_V1_MAX_PLAN_ACTIONS,
  CORE_V1_MAX_PROCESSING_ADVANCE,
  CORE_V1_MAX_PROCESSING_EVENTS,
} from './core-v1.action-economy.config.js';
import { CORE_V1_MAX_RESOLUTION_ACTORS } from './core-v1.effects.config.js';

export const CORE_V1_ENCOUNTER_SCHEMA_VERSION = 1 as const;
export const CORE_V1_ENCOUNTER_RULESET_CODE = 'core-v1' as const;
export const CORE_V1_ENCOUNTER_RULES_CODE = 'core-v1-encounter-v1' as const;

export const CORE_V1_MAX_ENCOUNTER_PARTICIPANTS = 64;
export const CORE_V1_MAX_ENCOUNTER_TARGETS = CORE_V1_MAX_RESOLUTION_ACTORS;
export const CORE_V1_MAX_ENCOUNTER_EVENTS = CORE_V1_MAX_EVENT_QUEUE_SIZE;
export const CORE_V1_MAX_ENCOUNTER_BATCH_EVENTS = CORE_V1_MAX_PROCESSING_EVENTS;
export const CORE_V1_MAX_ENCOUNTER_PLAN_ACTIONS = CORE_V1_MAX_PLAN_ACTIONS;
export const CORE_V1_MAX_ENCOUNTER_COMBO_EVENTS = CORE_V1_MAX_COMBO_EVENTS;
export const CORE_V1_MAX_ENCOUNTER_BATCH_ADVANCE = CORE_V1_MAX_PROCESSING_ADVANCE;
export const CORE_V1_MAX_ENCOUNTER_TICK = CORE_V1_MAX_COMBAT_TICK;
